export const FETCH_NUMBERS = 'FETCH_NUMBERS';
export const CLEAR_FETCHED_NUMBERS = 'CLEAR_FETCHED_NUMBERS';
export const SHOW_WRONG_NUMBER_FORMAT_ERROR = 'SHOW_WRONG_NUMBER_FORMAT_ERROR';
export const HIDE_WRONG_NUMBER_FORMAT_ERROR = 'HIDE_WRONG_NUMBER_FORMAT_ERROR';
export const SHOW_NO_SEARCH_RESULTS_ERROR = 'SHOW_NO_SEARCH_RESULTS_ERROR';
export const HIDE_NO_SEARCH_RESULTS_ERROR = 'HIDE_NO_SEARCH_RESULTS_ERROR';
export const SHOW_NEW_NUMBER_ADDED_MSG = 'SHOW_NEW_NUMBER_ADDED_MSG';
export const HIDE_NEW_NUMBER_ADDED_MSG = 'HIDE_NEW_NUMBER_ADDED_MSG';
